---
title: "Final Project Stat331"
format: 
  html:
    code-tools: true
    toc: true
    embed-resources: true
    html-table-processing: none
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

# Loading Packages and data

```{r}
library(tidyverse)
library(knitr)
life_exp_data_raw <- read.csv("../stat331-FinalProject/lex.csv")
gdp_data_raw <- read.csv("../stat331-FinalProject/gdp_pcap.csv")
```

# Cleaning the Data 

```{r}
clean_year <- function(str) {
  str <- case_when(str_detect(str, "k$") ~ 
                     as.numeric(str_replace_all(str, "k$", "")) * 1000, 
                   .default = as.numeric(str))
  return(str)
}
```


```{r}
# pivot year columns to a single year and life expectancy column
life_exp_data <- life_exp_data_raw |>
  pivot_longer(
    cols = X1800:X2100,
    names_to = "year",
    values_to = "life_expectancy"
  ) |>
  mutate(
    year = str_sub(year, start = 2),
    year = as.factor(year)
  )

# pivot year columns to a single year and gdp column
gdp_data <- gdp_data_raw |>
  mutate(across(
    .cols = X1800:X2100,
    .fns = ~ clean_year(.x))) |>
  pivot_longer(
    cols = X1800:X2100,
    names_to = "year",
    values_to = "gdp"
  ) |>
  mutate(
    year = str_sub(year, start = 2),
    year = as.factor(year),
    gdp = as.numeric(gdp)
  )

# join both tables by country and year
complete_data <- life_exp_data |>
  full_join(
    gdp_data,
    join_by(
      country == country,
      year == year
    )
  ) |> 
  na.omit()

head(complete_data) |>
  kable()

```